### PR TITLE
Upgraded the icon/logo, and improved the TV banner

### PR DESCRIPTION
**Pull request by SecularSteve**
As requested in #34, I've made the necessary changes and replacements myself (code included) to assure that the application looks a lot better on more platforms. Especially TVs.

Android Accordant at that. Adaptable too.

The icon itself is free to use by anybody, as long as you credit me first.

### CODE REVIEW

**Comment by ChernyshovYuriy** [comment]
Unfortunately, the changes provided wasn't tested on devices or emulators. There are rules as to the format of icons which have to be followed. See screenshots from TV and Automotive. As enhancement in the process, it is a good practice to branch off from main and propose changes in the dedicated branch.
Screenshot_20231122_174918
Screenshot_20231122_174946
Screenshot_20231122_175500
Screenshot_20231122_175516

**Comment by SecularSteve** [comment]
Darn it...
I knew the "foreground" XMLs were a bit disjointed.

**Comment by SecularSteve** [comment]
Darn it...
I knew the "foreground" XMLs were a bit disjointed.

**Comment by lchojnack** [comment]
Hello

If you change the icon, I'd like to suggest take into account adaptive/themed icons.

https://developer.android.com/develop/ui/views/launch/icon_design_adaptive
https://www.androidpolice.com/android-13-themed-icons-how-to-activate/

**Pull request closed without merging**
